global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'calculator'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['host.docker.internal:8085']  # or use 'localhost:8085' if not using Docker
