name: Java CI/CD with Maven & Docker

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build-test-docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repo
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Set up Java 17 with Maven cache to speed up builds
      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: maven

      # Step 3: Run unit tests using Maven
      - name: Run unit tests
        run: mvn test

      # Step 4: Build the app and skip the tests since we've already run them
      - name: Build the app
        run: mvn clean package -DskipTests

      # Step 5: Build and push Docker image to Docker Hub
      - name: Build & Push Docker image
        uses: mr-smithers-excellent/docker-build-push@v6
        with:
          image: ujjwal250802/calc-githubactions
          tags: latest
          registry: docker.io
          dockerfile: Dockerfile
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
